from __future__ import annotations

import os
import re
from datetime import UTC, datetime
from pathlib import Path

from mpga.core.logger import log

from .agents import SKILL_NAMES, copy_skills_to
from .runtime import (
    copy_vendored_runtime,
    global_vendored_cli_command,
    project_vendored_cli_command,
)

# --- Antigravity export -------------------------------------------------------


def export_antigravity(
    project_root: str,
    mpga_dir: str,
    index_content: str,
    project_name: str,
    plugin_root: str | None,
    is_global: bool,
    opts: dict | None = None,
) -> None:
    if opts is None:
        opts = {}
    if is_global:
        home = os.environ.get("HOME", "~")
        gemini_root = str(Path(home) / ".gemini")
        cli_command = global_vendored_cli_command(gemini_root) if plugin_root else "mpga"
        copy_vendored_runtime(gemini_root, plugin_root)
        ag_global_skills_dir = str(
            Path(home) / ".gemini" / "antigravity" / "skills"
        )
        copy_skills_to(ag_global_skills_dir, plugin_root, "antigravity", cli_command)
        log.success(f"Generated ~/.gemini/antigravity/skills/ ({len(SKILL_NAMES)} skills)")
        ag_global_rules_dir = Path(home) / ".antigravity" / "rules"
        ag_global_rules_dir.mkdir(parents=True, exist_ok=True)
        (ag_global_rules_dir / "mpga-global.md").write_text(
            _generate_antigravity_global(cli_command), encoding="utf-8"
        )
        log.success("Generated ~/.antigravity/rules/mpga-global.md")
    else:
        cli_command = project_vendored_cli_command() if plugin_root else "mpga"
        copy_vendored_runtime(project_root, plugin_root)
        # GEMINI.md constitution
        (Path(project_root) / "GEMINI.md").write_text(
            _generate_gemini_md(index_content, project_name, cli_command),
            encoding="utf-8",
        )
        log.success("Generated GEMINI.md")
        # Skills in .agent/skills/
        ag_skills_dir = str(Path(project_root) / ".agent" / "skills")
        copy_skills_to(ag_skills_dir, plugin_root, "antigravity", cli_command)
        log.success(f".agent/skills/ ({len(SKILL_NAMES)} skills)")
        # Rules in .antigravity/rules/
        rules_dir = Path(project_root) / ".antigravity" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        (rules_dir / "mpga-context.md").write_text(
            _generate_antigravity_context_md(index_content, project_name, cli_command),
            encoding="utf-8",
        )
        (rules_dir / "mpga-evidence.md").write_text(
            _generate_antigravity_evidence_md(cli_command), encoding="utf-8"
        )
        (rules_dir / "mpga-tdd.md").write_text(
            _generate_antigravity_tdd_md(cli_command), encoding="utf-8"
        )
        log.success("Generated .antigravity/rules/ (3 files)")
        # Workflows in .agents/workflows/ -- always generated for antigravity
        workflows_dir = Path(project_root) / ".agents" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)
        (workflows_dir / "mpga-plan.md").write_text(
            _generate_antigravity_plan_workflow(cli_command), encoding="utf-8"
        )
        (workflows_dir / "mpga-develop.md").write_text(
            _generate_antigravity_develop_workflow(cli_command), encoding="utf-8"
        )
        (workflows_dir / "mpga-review.md").write_text(
            _generate_antigravity_review_workflow(cli_command), encoding="utf-8"
        )
        log.success("Generated .agents/workflows/ (3 workflow files)")
        # Knowledge Items seeding
        if opts.get("knowledge"):
            scopes_dir = Path(mpga_dir) / "scopes"
            if scopes_dir.exists():
                _seed_antigravity_knowledge_items(project_root, str(scopes_dir))
                log.success("Seeded Knowledge Items from MPGA/scopes/")


# --- Antigravity generators ---------------------------------------------------


def _generate_gemini_md(
    index_content: str, _project_name: str, cli_command: str
) -> str:
    milestones_match = re.search(
        r"## Active milestone\n([\s\S]*?)(?=\n##|$)", index_content
    )
    milestone = milestones_match.group(1).strip() if milestones_match else "(none)"

    now = datetime.now(UTC).isoformat()

    return f"""# MPGA-Managed Project Context \u2014 the GREATEST Context, Everybody Says So

This project uses MPGA \u2014 the GREATEST context engineering system ever built. Believe me.
Do NOT edit this file manually \u2014 generated from MPGA/INDEX.md.
Run `{cli_command} sync && {cli_command} export --antigravity` to update.

## Before starting any task \u2014 READ THIS FIRST, very important
1. Read MPGA/INDEX.md \u2014 this is the project's truth map, TREMENDOUS truth map
2. Find the relevant MPGA/scopes/*.md for the feature area
3. Check MPGA/board/BOARD.md for task state and assignments

## Evidence protocol \u2014 no FAKE claims allowed
- Every claim about code behavior must cite an evidence link
- Format: [E] src/auth/jwt.ts:42-67 :: validateToken()
- If you cannot verify a claim, mark it: [Unknown] description
- After modifying code, check if evidence links need updating

## TDD protocol (mandatory) \u2014 Uncle Bob's way. The ONLY way.
1. Write failing test FIRST
2. Implement minimal code to pass
3. Refactor without changing behavior
4. Update MPGA scope docs with new evidence links

## Parallel execution protocol \u2014 tremendous efficiency, the best efficiency
- One writer per scope at a time
- Read-only analysis can run in parallel
- Prefer milestone plans that isolate independent scopes into separate lanes

## Active milestone
{milestone}

## Verification commands \u2014 each one a WINNER
- `npm test` \u2014 run test suite
- `{cli_command} evidence verify` \u2014 check evidence links
- `{cli_command} drift --quick` \u2014 check for drift
- `{cli_command} board show` \u2014 view task board

We're going to Make This Project GREAT AGAIN!

Generated: {now}
"""


def _generate_antigravity_context_md(
    index_content: str, _project_name: str, cli_command: str
) -> str:
    milestones_match = re.search(
        r"## Active milestone\n([\s\S]*?)(?=\n##|$)", index_content
    )
    milestone = milestones_match.group(1).strip() if milestones_match else "(none)"

    now = datetime.now(UTC).isoformat()

    return f"""# MPGA Project Context

This project uses evidence-backed context engineering via MPGA.

## Agent instructions
Before executing any task:
1. Read MPGA/INDEX.md \u2014 this is the project's truth map
2. Read the relevant MPGA/scopes/*.md for the feature area
3. Check MPGA/board/BOARD.md for task state and assignments

## Evidence protocol
- Every claim about code behavior must cite an evidence link
- Format: [E] src/auth/jwt.ts:42-67 :: validateToken()
- If you cannot verify a claim, mark it: [Unknown] description
- After modifying code, check if evidence links need updating

## Active milestone
{milestone}

## Verification commands
- `npm test` \u2014 run test suite
- `{cli_command} evidence verify` \u2014 check evidence links
- `{cli_command} drift --quick` \u2014 check for drift
- `{cli_command} board show` \u2014 view task board

## Parallel execution protocol
- One writer per scope at a time
- Background read-only audits are safe to parallelize
- Break work into scope-local queues where possible

Generated: {now}
"""


def _generate_antigravity_evidence_md(cli_command: str) -> str:
    return f"""# MPGA Evidence Protocol

## Evidence link format
```
[E] filepath:startLine-endLine :: symbolName()   # exact range + AST anchor (preferred)
[E] filepath :: symbolName                        # AST-only, resilient to refactors
[Unknown] description                             # explicitly unknown \u2014 never guess
[Stale:YYYY-MM-DD] filepath:range                # was valid, needs re-verification
```

## Rules
- EVERY claim about how code works must cite an evidence link
- When you cannot find evidence, write [Unknown] \u2014 never invent a claim
- After changing code, check whether evidence links in the affected scope still resolve
- Run `{cli_command} evidence heal --auto` to fix broken line ranges via AST

## Scope documents
Evidence links live in MPGA/scopes/*.md \u2014 read the relevant scope before touching code.
"""


def _generate_antigravity_tdd_md(_cli_command: str) -> str:
    return """# MPGA TDD Protocol

## Mandatory test-driven development cycle

### For every code change:
1. RED: Write a failing test that describes expected behavior
   - Cite relevant evidence from MPGA/scopes/ in test comments
   - Run test \u2014 it MUST fail
2. GREEN: Write minimal implementation to make the test pass
   - YAGNI \u2014 do not add anything the test doesn't require
   - Run test \u2014 it MUST pass
3. BLUE: Refactor without changing behavior
   - All tests must stay green after every refactoring step
   - Update evidence links in MPGA/scopes/ if code moved

### Rules
- NEVER write implementation code before a test exists
- NEVER add features not covered by tests
- ALWAYS update MPGA/board/ task cards with TDD stage progress
"""


def _generate_antigravity_global(cli_command: str) -> str:
    return f"""# MPGA Global Methodology

When you detect an MPGA/ directory in any project:

## Always do
- Read MPGA/INDEX.md before starting any task
- Use evidence links to ground every claim about code behavior
- Mark unknowns explicitly \u2014 never guess or hallucinate
- Follow TDD: test first, implement second, refactor third
- Check the task board at MPGA/board/BOARD.md
- Update scope docs when you change code
- Prefer the vendored runtime command: `{cli_command}`

## Evidence link format
[E] filepath:startLine-endLine :: symbolName()
[Unknown] description
[Stale:YYYY-MM-DD] filepath:range

## Never do
- Never paste entire directories into context \u2014 use tiered loading
- Never write implementation before tests
- Never claim code works without an evidence link
- Never ignore [Unknown] markers \u2014 they mean "we don't know yet"
"""


def _generate_antigravity_plan_workflow(cli_command: str) -> str:
    return f"""# MPGA Plan Workflow

## Trigger
Use this workflow when a milestone has been created and needs an implementation plan.

## Steps
1. Read MPGA/INDEX.md for project map and scope registry
2. Identify the milestone in MPGA/milestones/
3. Load relevant scope docs from MPGA/scopes/
4. Run research and read-only scope discovery in parallel where possible
5. Break work into tasks (2-10 min each)
   - Each task MUST cite exact files to modify (with evidence links)
   - Each task MUST specify expected test file locations
   - Each task MUST have mechanically verifiable acceptance criteria
   - Mark which tasks can run in parallel by scope
6. Save plan to MPGA/milestones/<id>/PLAN.md
7. Add tasks to board: `{cli_command} board add "<title>" --scope <name>`
"""


def _generate_antigravity_develop_workflow(cli_command: str) -> str:
    return f"""# MPGA Develop Workflow

## Trigger
Use this workflow when implementing a planned task from the MPGA board.

## Steps
1. Read the task card from MPGA/board/tasks/T*.md
2. Load the scopes listed in the task's `scopes` field
3. Claim a scope-local write lane \u2014 one writer per scope
4. Write failing test (cite scope evidence in comments)
5. Implement minimal code to pass
6. Refactor for quality
7. Let read-only scout/auditor checks run in parallel while you write
8. Update evidence links in the relevant scope doc
9. Update the task card: set tdd_stage, add evidence_produced
10. Move task to next board column
11. Run: `{cli_command} drift --quick`
12. Commit with conventional message
"""


def _generate_antigravity_review_workflow(cli_command: str) -> str:
    return f"""# MPGA Review Workflow

## Trigger
Use this workflow when a task reaches the review column.

## Stage 1 \u2014 Spec compliance
- Does implementation match the plan in MPGA/milestones/<id>/PLAN.md?
- Are all evidence links in scope docs still valid? (`{cli_command} evidence verify`)
- Were tests written BEFORE implementation? (check git log order)

## Stage 2 \u2014 Code quality
- Clean code principles (naming, single responsibility, DRY)
- Error handling for expected failure modes
- No security regressions
- Performance considerations

## Output
- PASS: move task to done, update board
- FAIL (critical): move task back to in-progress, note the blocker
- FAIL (warning): move to done with follow-up task created
"""


def _seed_antigravity_knowledge_items(project_root: str, scopes_dir: str) -> None:
    ki_dir = Path(project_root) / ".antigravity" / "knowledge"
    ki_dir.mkdir(parents=True, exist_ok=True)

    scopes_path = Path(scopes_dir)
    scopes = [f for f in scopes_path.iterdir() if f.suffix == ".md"]
    for scope_file in scopes:
        scope_name = scope_file.stem
        scope_content = scope_file.read_text(encoding="utf-8")
        evidence_links = re.findall(r"\[E\] .+", scope_content)[:10]

        if evidence_links:
            evidence_section = "\n".join(f"- {lnk}" for lnk in evidence_links)
        else:
            evidence_section = "- (run `mpga sync` to populate)"

        (ki_dir / f"mpga-{scope_name}.md").write_text(
            f"""# Knowledge: {scope_name} module

Source: MPGA/scopes/{scope_name}.md
Auto-seeded by `mpga export --antigravity --knowledge`

## Key evidence
{evidence_section}

## Full scope
Read MPGA/scopes/{scope_name}.md for the complete evidence-backed scope document.
""",
            encoding="utf-8",
        )
