"""Tests for the init, config, status, and health commands."""

import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from tests.conftest import write_file


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def seed_mpga_project(root: Path, *, scopes: list[str] | None = None, index_content: str | None = None):
    """Seed a minimal MPGA structure so commands that expect an initialized project work."""
    mpga = root / "MPGA"
    scopes_dir = mpga / "scopes"
    board_dir = mpga / "board"
    tasks_dir = board_dir / "tasks"

    scopes_dir.mkdir(parents=True, exist_ok=True)
    tasks_dir.mkdir(parents=True, exist_ok=True)
    (mpga / "milestones").mkdir(parents=True, exist_ok=True)
    (mpga / "sessions").mkdir(parents=True, exist_ok=True)

    # Config
    config = {
        "version": "1.0.0",
        "project": {
            "name": "test-project",
            "languages": ["typescript"],
            "entryPoints": [],
            "ignore": [],
        },
        "evidence": {
            "strategy": "hybrid",
            "lineRanges": True,
            "astAnchors": True,
            "autoHeal": True,
            "coverageThreshold": 0.2,
        },
        "drift": {"ciThreshold": 80, "hookMode": "quick", "autoSync": False},
    }
    write_file(mpga, "mpga.config.json", json.dumps(config, indent=2) + "\n")

    # INDEX.md
    if index_content is None:
        index_content = (
            "# Project: test-project\n\n"
            "## Identity\n"
            "- **Last sync:** 2026-01-15T10:00:00Z\n"
            "- **Evidence coverage:** 45%\n"
        )
    write_file(mpga, "INDEX.md", index_content)

    # GRAPH.md
    write_file(mpga, "GRAPH.md", "# Dependency graph\n")

    # Board
    board = {
        "version": "1.0.0",
        "milestone": None,
        "updated": "2026-01-01T00:00:00.000Z",
        "columns": {
            "backlog": [],
            "todo": [],
            "in-progress": [],
            "testing": [],
            "review": [],
            "done": [],
        },
        "stats": {
            "total": 0,
            "done": 0,
            "in_flight": 0,
            "blocked": 0,
            "progress_pct": 0,
            "evidence_produced": 0,
            "evidence_expected": 0,
        },
        "wip_limits": {"in-progress": 3, "testing": 3, "review": 2},
        "next_task_id": 1,
    }
    write_file(board_dir, "board.json", json.dumps(board, indent=2) + "\n")
    write_file(board_dir, "BOARD.md", "# Board\n\nNo tasks yet.\n")

    # Optional scope files
    if scopes:
        for scope in scopes:
            write_file(scopes_dir, f"{scope}.md", f"# Scope: {scope}\n\n- **Health:** ok\n")


# ---------------------------------------------------------------------------
# Tests: init command
# ---------------------------------------------------------------------------

class TestRegisterInit:
    """registerInit -- the GREATEST init command in history."""

    def test_creates_directory_structure(self, tmp_path: Path, monkeypatch):
        """Creates the directory structure."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        assert (tmp_path / "MPGA").is_dir()
        assert (tmp_path / "MPGA" / "scopes").is_dir()
        assert (tmp_path / "MPGA" / "board").is_dir()
        assert (tmp_path / "MPGA" / "board" / "tasks").is_dir()
        assert (tmp_path / "MPGA" / "milestones").is_dir()
        assert (tmp_path / "MPGA" / "sessions").is_dir()

    def test_creates_index_md(self, tmp_path: Path, monkeypatch):
        """Creates INDEX.md with project name and evidence coverage."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        index_path = tmp_path / "MPGA" / "INDEX.md"
        assert index_path.exists()

        content = index_path.read_text()
        project_name = tmp_path.name
        assert f"# Project: {project_name}" in content
        assert "**Evidence coverage:** 0%" in content
        assert "Agent trigger table" in content
        assert "Scope registry" in content
        assert "Generated by MPGA on" in content

    def test_creates_graph_md(self, tmp_path: Path, monkeypatch):
        """Creates GRAPH.md with a Mermaid placeholder."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        graph_path = tmp_path / "MPGA" / "GRAPH.md"
        assert graph_path.exists()

        content = graph_path.read_text()
        assert "# Dependency graph" in content
        assert "```mermaid" in content
        assert "Circular dependencies" in content
        assert "Orphan modules" in content

    def test_creates_config_json(self, tmp_path: Path, monkeypatch):
        """Creates mpga.config.json with correct defaults."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        config_path = tmp_path / "MPGA" / "mpga.config.json"
        assert config_path.exists()

        config = json.loads(config_path.read_text())
        assert config["version"] == "1.0.0"
        assert config["project"]["name"] == tmp_path.name
        assert config["evidence"]["strategy"] == "hybrid"
        assert config["drift"]["ciThreshold"] == 80

    def test_creates_board_json(self, tmp_path: Path, monkeypatch):
        """Creates board.json with empty columns and zero stats."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        board_path = tmp_path / "MPGA" / "board" / "board.json"
        assert board_path.exists()

        board = json.loads(board_path.read_text())
        assert board["version"] == "1.0.0"
        assert board["milestone"] is None
        assert board["stats"]["total"] == 0
        assert board["stats"]["done"] == 0
        assert "backlog" in board["columns"]
        assert "done" in board["columns"]
        assert board["wip_limits"] == {"in-progress": 3, "testing": 3, "review": 2}
        assert board["next_task_id"] == 1

    def test_creates_board_md(self, tmp_path: Path, monkeypatch):
        """Creates BOARD.md placeholder."""
        monkeypatch.chdir(tmp_path)
        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        assert result.exit_code == 0

        board_md_path = tmp_path / "MPGA" / "board" / "BOARD.md"
        assert board_md_path.exists()
        content = board_md_path.read_text()
        assert "# Board" in content
        assert "No tasks yet" in content

    def test_does_not_overwrite_if_already_initialized(self, tmp_path: Path, monkeypatch, capsys):
        """Does not overwrite if already initialized."""
        monkeypatch.chdir(tmp_path)
        seed_mpga_project(tmp_path)

        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, [])
        # Should warn that project is already initialized (exit 0, but with warning output)
        assert result.exit_code == 0
        assert "already initialized" in result.output

    def test_from_existing_detects_project_type(self, tmp_path: Path, monkeypatch):
        """--from-existing detects project type via scanner."""
        monkeypatch.chdir(tmp_path)

        # Create some source files so the scanner finds something
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "index.ts").write_text("export function main() {}\n")

        from mpga.commands.init import init_cmd

        runner = CliRunner()
        result = runner.invoke(init_cmd, ["--from-existing"])
        assert result.exit_code == 0

        config_path = tmp_path / "MPGA" / "mpga.config.json"
        config = json.loads(config_path.read_text())
        assert isinstance(config["project"]["languages"], list)


# ---------------------------------------------------------------------------
# Tests: config command
# ---------------------------------------------------------------------------

class TestRegisterConfig:
    """registerConfig -- total CONTROL over your project."""

    def test_config_show_json(self, tmp_path: Path, monkeypatch):
        """config show --json outputs valid JSON."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        from mpga.commands.config_cmd import config_show

        runner = CliRunner()
        result = runner.invoke(config_show, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["project"]["name"] == "test-project"
        assert parsed["version"] == "1.0.0"

    def test_config_show_kv(self, tmp_path: Path, monkeypatch):
        """config show without --json outputs key-value lines."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        from mpga.commands.config_cmd import config_show

        runner = CliRunner()
        result = runner.invoke(config_show, [])
        assert result.exit_code == 0
        assert "project.name" in result.output

    def test_config_set_numeric(self, tmp_path: Path, monkeypatch):
        """config set updates a numeric config value."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        from mpga.commands.config_cmd import config_set

        runner = CliRunner()
        result = runner.invoke(config_set, ["drift.ciThreshold", "90"])
        assert result.exit_code == 0

        config_path = tmp_path / "MPGA" / "mpga.config.json"
        config = json.loads(config_path.read_text())
        assert config["drift"]["ciThreshold"] == 90

    def test_config_set_unknown_key_errors(self, tmp_path: Path, monkeypatch):
        """config set exits with error for unknown key."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        from mpga.commands.config_cmd import config_set

        runner = CliRunner()
        result = runner.invoke(config_set, ["nonexistent.key", "val"])
        assert result.exit_code != 0


# ---------------------------------------------------------------------------
# Tests: status command
# ---------------------------------------------------------------------------

class TestRegisterStatus:
    """registerStatus -- the BEST status reports."""

    def test_exits_when_not_initialized(self, tmp_path: Path, monkeypatch):
        """Exits with error when MPGA is not initialized."""
        monkeypatch.chdir(tmp_path)

        from mpga.commands.status import status_cmd

        runner = CliRunner()
        result = runner.invoke(status_cmd, [])
        assert result.exit_code != 0

    def test_json_returns_correct_structure(self, tmp_path: Path, monkeypatch):
        """--json returns correct structure."""
        seed_mpga_project(tmp_path, scopes=["core", "auth"])
        monkeypatch.chdir(tmp_path)

        from mpga.commands.status import status_cmd

        runner = CliRunner()
        result = runner.invoke(status_cmd, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["initialized"] is True
        assert parsed["lastSync"] == "2026-01-15T10:00:00Z"
        assert parsed["evidenceCoverage"] == "45%"
        assert parsed["scopes"] == 2
        assert parsed["config"]["name"] == "test-project"
        assert "board" in parsed

    def test_json_zero_scopes(self, tmp_path: Path, monkeypatch):
        """--json returns zero scopes when none exist."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        from mpga.commands.status import status_cmd

        runner = CliRunner()
        result = runner.invoke(status_cmd, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["scopes"] == 0


# ---------------------------------------------------------------------------
# Tests: health command
# ---------------------------------------------------------------------------

class TestRegisterHealth:
    """registerHealth -- keeping our project in PERFECT health."""

    def test_exits_when_not_initialized(self, tmp_path: Path, monkeypatch):
        """Exits with error when MPGA is not initialized."""
        monkeypatch.chdir(tmp_path)

        from mpga.commands.health import health_cmd

        runner = CliRunner()
        result = runner.invoke(health_cmd, [])
        assert result.exit_code != 0

    def test_json_returns_correct_health_report(self, tmp_path: Path, monkeypatch):
        """--json returns correct health report."""
        seed_mpga_project(tmp_path, scopes=["core", "utils"])
        monkeypatch.chdir(tmp_path)

        from mpga.commands.health import health_cmd

        runner = CliRunner()
        result = runner.invoke(health_cmd, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["initialized"] is True
        assert isinstance(parsed["evidenceHealth"], (int, float))
        assert isinstance(parsed["ciPass"], bool)
        assert parsed["scopes"] == 2
        assert "board" in parsed
        assert parsed["lastSync"] == "2026-01-15T10:00:00Z"
        assert "overallGrade" in parsed
        assert parsed["overallGrade"] in ("A", "B", "C", "D")

    def test_json_grade_a_for_100_percent(self, tmp_path: Path, monkeypatch):
        """--json includes correct grade for 100% health."""
        seed_mpga_project(tmp_path)
        monkeypatch.chdir(tmp_path)

        # Mock drift check to return 100% health
        from mpga.evidence.drift import DriftReport

        mock_report = DriftReport(
            timestamp="2026-01-01T00:00:00Z",
            project_root=str(tmp_path),
            overall_health_pct=100,
            ci_pass=True,
            scopes=[],
            total_links=0,
            valid_links=0,
            ci_threshold=80,
        )
        monkeypatch.setattr("mpga.commands.health.run_drift_check", lambda *a, **kw: mock_report)

        from mpga.commands.health import health_cmd

        runner = CliRunner()
        result = runner.invoke(health_cmd, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["overallGrade"] == "A"

    def test_json_last_sync_never(self, tmp_path: Path, monkeypatch):
        """--json reports lastSync as 'never' when INDEX.md has placeholder."""
        seed_mpga_project(
            tmp_path,
            index_content="# Project: test\n\n- **Last sync:** (run `mpga sync` to populate)\n",
        )
        monkeypatch.chdir(tmp_path)

        from mpga.commands.health import health_cmd

        runner = CliRunner()
        result = runner.invoke(health_cmd, ["--json"])
        assert result.exit_code == 0

        parsed = json.loads(result.output)
        assert parsed["lastSync"] == "never"
