from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import click

from mpga.core.config import default_config, save_config
from mpga.core.logger import banner, log
from mpga.core.scanner import detect_project_type, scan


def _index_template(name: str, project_type: str, date: str) -> str:
    return f"""# Project: {name}

## Identity
- **Type:** {project_type}
- **Size:** (run `mpga sync` to populate)
- **Languages:** (run `mpga sync` to populate)
- **Last sync:** (not yet synced)
- **Evidence coverage:** 0% (target: 20%)

## Key files
| File | Role | Evidence |
|------|------|----------|
| (run `mpga sync` to populate) | | |

## Conventions
- (Add your project conventions here)

## Agent trigger table
| Task pattern | Agent | Scopes to load |
|-------------|-------|-----------------|
| "add/modify authentication" | red-dev \u2192 green-dev \u2192 blue-dev | auth, database |
| "explore how X works" | scout | (auto-detect) |
| "plan feature X" | researcher \u2192 architect | (auto-detect) |
| "fix bug in X" | scout \u2192 red-dev \u2192 green-dev | (auto-detect) |
| "refactor X" | architect \u2192 blue-dev | (auto-detect) |

## Scope registry
| Scope | Status | Evidence links | Last verified |
|-------|--------|---------------|---------------|
| (run `mpga sync` to generate scopes) | | | |

## Active milestone
- (none)

## Known unknowns
- [ ] (run `mpga sync` to detect unknowns)

---
*Generated by MPGA on {date}. Run `mpga sync` to populate with real evidence.*
"""


def _graph_template() -> str:
    return """# Dependency graph

## Module dependencies
(run `mpga sync` to generate dependency graph)

## Circular dependencies
(none detected yet)

## Orphan modules
(none detected yet)

## Mermaid export
```mermaid
graph TD
    (sync to populate)
```
"""


@click.command("init")
@click.option("--from-zero", is_flag=True, help="New project with no existing code")
@click.option("--from-existing", is_flag=True, help="Scan and map an existing codebase")
def init_cmd(from_zero: bool, from_existing: bool) -> None:
    """Bootstrap MPGA/ knowledge layer in current project."""
    project_root = Path.cwd()
    mpga_dir = project_root / "MPGA"
    config_path = mpga_dir / "mpga.config.json"

    banner()

    if config_path.exists():
        log.warn("MPGA/ already initialized \u2014 we're already GREAT!")
        log.dim("Run `mpga sync` to refresh the knowledge layer.")
        return

    log.info(f"Making {project_root} GREAT AGAIN!")

    # Create directory structure
    dirs = [
        mpga_dir,
        mpga_dir / "scopes",
        mpga_dir / "board",
        mpga_dir / "board" / "tasks",
        mpga_dir / "milestones",
        mpga_dir / "sessions",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        log.dim(f"  created {d.relative_to(project_root)}/")

    # Detect project info if from-existing
    project_name = project_root.name
    project_type = "Application"
    config = default_config()
    config.project.name = project_name

    if from_existing:
        log.info("Scanning the existing codebase \u2014 going to be BEAUTIFUL...")
        try:
            scan_result = scan(str(project_root), config.project.ignore)
            project_type = detect_project_type(scan_result)
            log.success(
                f"Detected: {project_type} ({scan_result.total_files} files, {scan_result.total_lines:,} lines)"
            )

            # Auto-detect languages
            langs = [lang for lang in scan_result.languages if lang not in ("other", "markdown")]
            if langs:
                config.project.languages = langs
            if scan_result.entry_points:
                config.project.entry_points = scan_result.entry_points
        except Exception:
            log.warn("Scan failed \u2014 no problem, we have the BEST defaults!")

    # Write config
    save_config(config, config_path)
    log.success("Created MPGA/mpga.config.json \u2014 the BEST configuration, believe me!")

    now = datetime.now(UTC).isoformat()

    # Write INDEX.md
    (mpga_dir / "INDEX.md").write_text(_index_template(project_name, project_type, now))
    log.success("Created MPGA/INDEX.md \u2014 the most BEAUTIFUL index!")

    # Write GRAPH.md
    (mpga_dir / "GRAPH.md").write_text(_graph_template())
    log.success("Created MPGA/GRAPH.md \u2014 a TREMENDOUS graph, folks!")

    # Write initial board.json
    board_state = {
        "version": "1.0.0",
        "milestone": None,
        "updated": now,
        "columns": {
            "backlog": [],
            "todo": [],
            "in-progress": [],
            "testing": [],
            "review": [],
            "done": [],
        },
        "stats": {
            "total": 0,
            "done": 0,
            "in_flight": 0,
            "blocked": 0,
            "progress_pct": 0,
            "evidence_produced": 0,
            "evidence_expected": 0,
        },
        "wip_limits": {"in-progress": 3, "testing": 3, "review": 2},
        "next_task_id": 1,
    }
    (mpga_dir / "board" / "board.json").write_text(
        json.dumps(board_state, indent=2) + "\n"
    )
    log.success("Created MPGA/board/board.json \u2014 a WINNING board!")

    # Write BOARD.md
    (mpga_dir / "board" / "BOARD.md").write_text(
        "# Board\n\nNo tasks yet. Run `/mpga:plan` to generate tasks from a milestone.\n"
    )
    log.success("Created MPGA/board/BOARD.md \u2014 HUGE task board, the biggest!")

    # Setup spoke (Trump voice TTS)
    spoke_dir = project_root / ".mpga-runtime" / "spoke"
    spoke_setup = spoke_dir / "setup.sh"
    spoke_venv = spoke_dir / "venv" / "bin" / "python3"
    if spoke_setup.exists():
        click.echo("")
        log.info("Setting up Trump voice (F5-TTS) \u2014 the BEST voice, believe me...")
        try:
            if not spoke_venv.exists():
                subprocess.run(["bash", str(spoke_setup)], check=True)
            else:
                log.dim("  Spoke already installed.")
                # Just make sure server is running
                server_script = spoke_dir / "server.py"
                health = subprocess.run(
                    ["curl", "-sf", "http://127.0.0.1:5151/health"],
                    capture_output=True,
                    timeout=1,
                )
                if health.returncode != 0:
                    log.dim("  Starting spoke server...")
                    child = subprocess.Popen(
                        [str(spoke_venv), str(server_script), "--port", "5151"],
                        start_new_session=True,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    (spoke_dir / ".server.pid").write_text(str(child.pid))
            log.success("Spoke ready \u2014 Trump voice ACTIVATED!")
        except Exception:
            log.warn("Spoke setup failed \u2014 voice will be available later via `mpga spoke --setup`")

    click.echo("")
    log.success("MPGA initialized \u2014 your project is about to be GREAT AGAIN!")
    click.echo("")
    log.dim("Your next steps \u2014 each one a WINNER:")
    if from_existing:
        log.dim("  mpga sync          \u2014 generate knowledge layer, it's going to be FANTASTIC")
        log.dim("  mpga status        \u2014 see how GREAT your project is looking")
    else:
        log.dim("  mpga status        \u2014 see how GREAT your project is looking")
        log.dim("  mpga milestone new \u2014 start your first milestone, HUGE things ahead")
    log.dim('  mpga spoke "text"  \u2014 hear it in Trump voice, TREMENDOUS')
