import fs from 'fs';
import path from 'path';
import { log } from '../../core/logger.js';
import { SKILL_NAMES, copySkillsTo } from './agents.js';
import {
  copyVendoredRuntime,
  globalVendoredCliCommand,
  projectVendoredCliCommand,
} from './runtime.js';

// ─── Antigravity export ──────────────────────────────────────────────────────

export function exportAntigravity(
  projectRoot: string,
  mpgaDir: string,
  indexContent: string,
  projectName: string,
  pluginRoot: string | null,
  isGlobal: boolean,
  opts: { knowledge?: boolean },
): void {
  if (isGlobal) {
    const geminiRoot = path.join(process.env.HOME ?? '~', '.gemini');
    const cliCommand = pluginRoot ? globalVendoredCliCommand(geminiRoot) : 'npx mpga';
    copyVendoredRuntime(geminiRoot, pluginRoot);
    const agGlobalSkillsDir = path.join(
      process.env.HOME ?? '~',
      '.gemini',
      'antigravity',
      'skills',
    );
    copySkillsTo(agGlobalSkillsDir, pluginRoot, 'antigravity', cliCommand);
    log.success(`Generated ~/.gemini/antigravity/skills/ (${SKILL_NAMES.length} skills)`);
    const agGlobalRulesDir = path.join(process.env.HOME ?? '~', '.antigravity', 'rules');
    fs.mkdirSync(agGlobalRulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(agGlobalRulesDir, 'mpga-global.md'),
      generateAntigravityGlobal(cliCommand),
    );
    log.success('Generated ~/.antigravity/rules/mpga-global.md');
  } else {
    const cliCommand = pluginRoot ? projectVendoredCliCommand() : 'npx mpga';
    copyVendoredRuntime(projectRoot, pluginRoot);
    // GEMINI.md constitution
    fs.writeFileSync(
      path.join(projectRoot, 'GEMINI.md'),
      generateGeminiMd(indexContent, projectName, cliCommand),
    );
    log.success('Generated GEMINI.md');
    // Skills in .agent/skills/
    const agSkillsDir = path.join(projectRoot, '.agent', 'skills');
    copySkillsTo(agSkillsDir, pluginRoot, 'antigravity', cliCommand);
    log.success(`.agent/skills/ (${SKILL_NAMES.length} skills)`);
    // Rules in .antigravity/rules/
    const rulesDir = path.join(projectRoot, '.antigravity', 'rules');
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(rulesDir, 'mpga-context.md'),
      generateAntigravityContextMd(indexContent, projectName, cliCommand),
    );
    fs.writeFileSync(
      path.join(rulesDir, 'mpga-evidence.md'),
      generateAntigravityEvidenceMd(cliCommand),
    );
    fs.writeFileSync(path.join(rulesDir, 'mpga-tdd.md'), generateAntigravityTddMd(cliCommand));
    log.success('Generated .antigravity/rules/ (3 files)');
    // Workflows in .agents/workflows/ — always generated for antigravity
    const workflowsDir = path.join(projectRoot, '.agents', 'workflows');
    fs.mkdirSync(workflowsDir, { recursive: true });
    fs.writeFileSync(
      path.join(workflowsDir, 'mpga-plan.md'),
      generateAntigravityPlanWorkflow(cliCommand),
    );
    fs.writeFileSync(
      path.join(workflowsDir, 'mpga-develop.md'),
      generateAntigravityDevelopWorkflow(cliCommand),
    );
    fs.writeFileSync(
      path.join(workflowsDir, 'mpga-review.md'),
      generateAntigravityReviewWorkflow(cliCommand),
    );
    log.success('Generated .agents/workflows/ (3 workflow files)');
    // Knowledge Items seeding
    if (opts.knowledge) {
      const scopesDir = path.join(mpgaDir, 'scopes');
      if (fs.existsSync(scopesDir)) {
        seedAntigravityKnowledgeItems(projectRoot, scopesDir);
        log.success('Seeded Knowledge Items from MPGA/scopes/');
      }
    }
  }
}

// ─── Antigravity generators ───────────────────────────────────────────────────

function generateGeminiMd(indexContent: string, _projectName: string, cliCommand: string): string {
  const milestonesMatch = indexContent.match(/## Active milestone\n([\s\S]*?)(?=\n##|$)/);
  const milestone = milestonesMatch ? milestonesMatch[1].trim() : '(none)';

  return `# MPGA-Managed Project Context

This project uses MPGA for evidence-backed context engineering.
Do NOT edit this file manually — generated from MPGA/INDEX.md.
Run \`${cliCommand} sync && ${cliCommand} export --antigravity\` to update.

## Before starting any task
1. Read MPGA/INDEX.md — this is the project's truth map
2. Find the relevant MPGA/scopes/*.md for the feature area
3. Check MPGA/board/BOARD.md for task state and assignments

## Evidence protocol
- Every claim about code behavior must cite an evidence link
- Format: [E] src/auth/jwt.ts:42-67 :: validateToken()
- If you cannot verify a claim, mark it: [Unknown] description
- After modifying code, check if evidence links need updating

## TDD protocol (mandatory)
1. Write failing test FIRST
2. Implement minimal code to pass
3. Refactor without changing behavior
4. Update MPGA scope docs with new evidence links

## Parallel execution protocol
- One writer per scope at a time
- Read-only analysis can run in parallel
- Prefer milestone plans that isolate independent scopes into separate lanes

## Active milestone
${milestone}

## Verification commands
- \`npm test\` — run test suite
- \`${cliCommand} evidence verify\` — check evidence links
- \`${cliCommand} drift --quick\` — check for drift
- \`${cliCommand} board show\` — view task board

Generated: ${new Date().toISOString()}
`;
}

function generateAntigravityContextMd(
  indexContent: string,
  _projectName: string,
  cliCommand: string,
): string {
  const milestonesMatch = indexContent.match(/## Active milestone\n([\s\S]*?)(?=\n##|$)/);
  const milestone = milestonesMatch ? milestonesMatch[1].trim() : '(none)';

  return `# MPGA Project Context

This project uses evidence-backed context engineering via MPGA.

## Agent instructions
Before executing any task:
1. Read MPGA/INDEX.md — this is the project's truth map
2. Read the relevant MPGA/scopes/*.md for the feature area
3. Check MPGA/board/BOARD.md for task state and assignments

## Evidence protocol
- Every claim about code behavior must cite an evidence link
- Format: [E] src/auth/jwt.ts:42-67 :: validateToken()
- If you cannot verify a claim, mark it: [Unknown] description
- After modifying code, check if evidence links need updating

## Active milestone
${milestone}

## Verification commands
- \`npm test\` — run test suite
- \`${cliCommand} evidence verify\` — check evidence links
- \`${cliCommand} drift --quick\` — check for drift
- \`${cliCommand} board show\` — view task board

## Parallel execution protocol
- One writer per scope at a time
- Background read-only audits are safe to parallelize
- Break work into scope-local queues where possible

Generated: ${new Date().toISOString()}
`;
}

function generateAntigravityEvidenceMd(cliCommand: string): string {
  return `# MPGA Evidence Protocol

## Evidence link format
\`\`\`
[E] filepath:startLine-endLine :: symbolName()   # exact range + AST anchor (preferred)
[E] filepath :: symbolName                        # AST-only, resilient to refactors
[Unknown] description                             # explicitly unknown — never guess
[Stale:YYYY-MM-DD] filepath:range                # was valid, needs re-verification
\`\`\`

## Rules
- EVERY claim about how code works must cite an evidence link
- When you cannot find evidence, write [Unknown] — never invent a claim
- After changing code, check whether evidence links in the affected scope still resolve
- Run \`${cliCommand} evidence heal --auto\` to fix broken line ranges via AST

## Scope documents
Evidence links live in MPGA/scopes/*.md — read the relevant scope before touching code.
`;
}

function generateAntigravityTddMd(_cliCommand: string): string {
  return `# MPGA TDD Protocol

## Mandatory test-driven development cycle

### For every code change:
1. RED: Write a failing test that describes expected behavior
   - Cite relevant evidence from MPGA/scopes/ in test comments
   - Run test — it MUST fail
2. GREEN: Write minimal implementation to make the test pass
   - YAGNI — do not add anything the test doesn't require
   - Run test — it MUST pass
3. BLUE: Refactor without changing behavior
   - All tests must stay green after every refactoring step
   - Update evidence links in MPGA/scopes/ if code moved

### Rules
- NEVER write implementation code before a test exists
- NEVER add features not covered by tests
- ALWAYS update MPGA/board/ task cards with TDD stage progress
`;
}

function generateAntigravityGlobal(cliCommand: string): string {
  return `# MPGA Global Methodology

When you detect an MPGA/ directory in any project:

## Always do
- Read MPGA/INDEX.md before starting any task
- Use evidence links to ground every claim about code behavior
- Mark unknowns explicitly — never guess or hallucinate
- Follow TDD: test first, implement second, refactor third
- Check the task board at MPGA/board/BOARD.md
- Update scope docs when you change code
- Prefer the vendored runtime command: \`${cliCommand}\`

## Evidence link format
[E] filepath:startLine-endLine :: symbolName()
[Unknown] description
[Stale:YYYY-MM-DD] filepath:range

## Never do
- Never paste entire directories into context — use tiered loading
- Never write implementation before tests
- Never claim code works without an evidence link
- Never ignore [Unknown] markers — they mean "we don't know yet"
`;
}

function generateAntigravityPlanWorkflow(cliCommand: string): string {
  return `# MPGA Plan Workflow

## Trigger
Use this workflow when a milestone has been created and needs an implementation plan.

## Steps
1. Read MPGA/INDEX.md for project map and scope registry
2. Identify the milestone in MPGA/milestones/
3. Load relevant scope docs from MPGA/scopes/
4. Run research and read-only scope discovery in parallel where possible
5. Break work into tasks (2-10 min each)
   - Each task MUST cite exact files to modify (with evidence links)
   - Each task MUST specify expected test file locations
   - Each task MUST have mechanically verifiable acceptance criteria
   - Mark which tasks can run in parallel by scope
6. Save plan to MPGA/milestones/<id>/PLAN.md
7. Add tasks to board: \`${cliCommand} board add "<title>" --scope <name>\`
`;
}

function generateAntigravityDevelopWorkflow(cliCommand: string): string {
  return `# MPGA Develop Workflow

## Trigger
Use this workflow when implementing a planned task from the MPGA board.

## Steps
1. Read the task card from MPGA/board/tasks/T*.md
2. Load the scopes listed in the task's \`scopes\` field
3. Claim a scope-local write lane — one writer per scope
4. Write failing test (cite scope evidence in comments)
5. Implement minimal code to pass
6. Refactor for quality
7. Let read-only scout/auditor checks run in parallel while you write
8. Update evidence links in the relevant scope doc
9. Update the task card: set tdd_stage, add evidence_produced
10. Move task to next board column
11. Run: \`${cliCommand} drift --quick\`
12. Commit with conventional message
`;
}

function generateAntigravityReviewWorkflow(cliCommand: string): string {
  return `# MPGA Review Workflow

## Trigger
Use this workflow when a task reaches the review column.

## Stage 1 — Spec compliance
- Does implementation match the plan in MPGA/milestones/<id>/PLAN.md?
- Are all evidence links in scope docs still valid? (\`${cliCommand} evidence verify\`)
- Were tests written BEFORE implementation? (check git log order)

## Stage 2 — Code quality
- Clean code principles (naming, single responsibility, DRY)
- Error handling for expected failure modes
- No security regressions
- Performance considerations

## Output
- PASS: move task to done, update board
- FAIL (critical): move task back to in-progress, note the blocker
- FAIL (warning): move to done with follow-up task created
`;
}

function seedAntigravityKnowledgeItems(projectRoot: string, scopesDir: string): void {
  const kiDir = path.join(projectRoot, '.antigravity', 'knowledge');
  fs.mkdirSync(kiDir, { recursive: true });

  const scopes = fs.readdirSync(scopesDir).filter((f) => f.endsWith('.md'));
  for (const scopeFile of scopes) {
    const scopeName = scopeFile.replace('.md', '');
    const scopeContent = fs.readFileSync(path.join(scopesDir, scopeFile), 'utf-8');
    const evidenceLinks = (scopeContent.match(/\[E\] .+/g) ?? []).slice(0, 10);

    fs.writeFileSync(
      path.join(kiDir, `mpga-${scopeName}.md`),
      `# Knowledge: ${scopeName} module

Source: MPGA/scopes/${scopeName}.md
Auto-seeded by \`mpga export --antigravity --knowledge\`

## Key evidence
${evidenceLinks.map((l) => `- ${l}`).join('\n') || '- (run `mpga sync` to populate)'}

## Full scope
Read MPGA/scopes/${scopeName}.md for the complete evidence-backed scope document.
`,
    );
  }
}
