import fs from 'fs';
import path from 'path';
import { Command } from 'commander';
import { log, banner } from '../core/logger.js';
import { DEFAULT_CONFIG, saveConfig, MpgaConfig } from '../core/config.js';
import { scan, detectProjectType } from '../core/scanner.js';

const INDEX_TEMPLATE = (name: string, projectType: string, date: string) => `# Project: ${name}

## Identity
- **Type:** ${projectType}
- **Size:** (run \`mpga sync\` to populate)
- **Languages:** (run \`mpga sync\` to populate)
- **Last sync:** (not yet synced)
- **Evidence coverage:** 0% (target: 20%)

## Key files
| File | Role | Evidence |
|------|------|----------|
| (run \`mpga sync\` to populate) | | |

## Conventions
- (Add your project conventions here)

## Agent trigger table
| Task pattern | Agent | Scopes to load |
|-------------|-------|-----------------|
| "add/modify authentication" | green-dev → red-dev → blue-dev | auth, database |
| "explore how X works" | scout | (auto-detect) |
| "plan feature X" | researcher → architect | (auto-detect) |
| "fix bug in X" | scout → green-dev → red-dev | (auto-detect) |
| "refactor X" | architect → blue-dev | (auto-detect) |

## Scope registry
| Scope | Status | Evidence links | Last verified |
|-------|--------|---------------|---------------|
| (run \`mpga sync\` to generate scopes) | | | |

## Active milestone
- (none)

## Known unknowns
- [ ] (run \`mpga sync\` to detect unknowns)

---
*Generated by MPGA on ${date}. Run \`mpga sync\` to populate with real evidence.*
`;

const GRAPH_TEMPLATE = () => `# Dependency graph

## Module dependencies
(run \`mpga sync\` to generate dependency graph)

## Circular dependencies
(none detected yet)

## Orphan modules
(none detected yet)

## Mermaid export
\`\`\`mermaid
graph TD
    (sync to populate)
\`\`\`
`;

export function registerInit(program: Command): void {
  program
    .command('init')
    .description('Bootstrap MPGA/ knowledge layer in current project')
    .option('--from-zero', 'New project with no existing code')
    .option('--from-existing', 'Scan and map an existing codebase')
    .action(async (opts) => {
      const projectRoot = process.cwd();
      const mpgaDir = path.join(projectRoot, 'MPGA');
      const configPath = path.join(mpgaDir, 'mpga.config.json');

      banner();

      if (fs.existsSync(configPath)) {
        log.warn('MPGA/ already initialized in this project.');
        log.dim('Run `mpga sync` to refresh the knowledge layer.');
        return;
      }

      log.info(`Initializing MPGA in ${projectRoot}`);

      // Create directory structure
      const dirs = [
        mpgaDir,
        path.join(mpgaDir, 'scopes'),
        path.join(mpgaDir, 'board'),
        path.join(mpgaDir, 'board', 'tasks'),
        path.join(mpgaDir, 'milestones'),
        path.join(mpgaDir, 'sessions'),
      ];
      for (const dir of dirs) {
        fs.mkdirSync(dir, { recursive: true });
        log.dim(`  created ${path.relative(projectRoot, dir)}/`);
      }

      // Detect project info if from-existing
      const projectName = path.basename(projectRoot);
      let projectType = 'Application';
      const config: MpgaConfig = {
        ...DEFAULT_CONFIG,
        project: {
          ...DEFAULT_CONFIG.project,
          name: projectName,
        },
      };

      if (opts.fromExisting) {
        log.info('Scanning existing codebase...');
        try {
          const scanResult = await scan(projectRoot, config.project.ignore);
          projectType = detectProjectType(scanResult);
          log.success(
            `Detected: ${projectType} (${scanResult.totalFiles} files, ${scanResult.totalLines.toLocaleString()} lines)`,
          );

          // Auto-detect languages
          const langs = Object.keys(scanResult.languages).filter(
            (l) => l !== 'other' && l !== 'markdown',
          );
          if (langs.length > 0) config.project.languages = langs;
          if (scanResult.entryPoints.length > 0)
            config.project.entryPoints = scanResult.entryPoints;
        } catch (e) {
          log.warn('Scan failed, proceeding with defaults');
        }
      }

      // Write config
      saveConfig(config, configPath);
      log.success('Created MPGA/mpga.config.json');

      const now = new Date().toISOString();

      // Write INDEX.md
      fs.writeFileSync(
        path.join(mpgaDir, 'INDEX.md'),
        INDEX_TEMPLATE(projectName, projectType, now),
      );
      log.success('Created MPGA/INDEX.md');

      // Write GRAPH.md
      fs.writeFileSync(path.join(mpgaDir, 'GRAPH.md'), GRAPH_TEMPLATE());
      log.success('Created MPGA/GRAPH.md');

      // Write initial board.json
      const boardState = {
        version: '1.0.0',
        milestone: null,
        updated: now,
        columns: { backlog: [], todo: [], 'in-progress': [], testing: [], review: [], done: [] },
        stats: {
          total: 0,
          done: 0,
          in_flight: 0,
          blocked: 0,
          progress_pct: 0,
          evidence_produced: 0,
          evidence_expected: 0,
        },
        wip_limits: { 'in-progress': 3, testing: 3, review: 2 },
        next_task_id: 1,
      };
      fs.writeFileSync(
        path.join(mpgaDir, 'board', 'board.json'),
        JSON.stringify(boardState, null, 2) + '\n',
      );
      log.success('Created MPGA/board/board.json');

      // Write BOARD.md
      fs.writeFileSync(
        path.join(mpgaDir, 'board', 'BOARD.md'),
        '# Board\n\nNo tasks yet. Run `/mpga:plan` to generate tasks from a milestone.\n',
      );
      log.success('Created MPGA/board/BOARD.md');

      console.log('');
      log.success('MPGA initialized successfully!');
      console.log('');
      log.dim('Next steps:');
      if (opts.fromExisting) {
        log.dim('  mpga sync          — generate knowledge layer from your codebase');
        log.dim('  mpga status        — view project health dashboard');
      } else {
        log.dim('  mpga status        — view current state');
        log.dim('  mpga milestone new — start your first milestone');
      }
    });
}
