import fs from 'fs';
import path from 'path';
import { log } from '../../core/logger.js';
import { SKILL_NAMES, copySkillsTo, rewriteCliReferences } from './agents.js';
import {
  copyVendoredRuntime,
  globalVendoredCliCommand,
  projectVendoredCliCommand,
} from './runtime.js';

// ─── Claude Code export ───────────────────────────────────────────────────────

export function exportClaude(
  projectRoot: string,
  indexContent: string,
  projectName: string,
  pluginRoot: string | null,
  isGlobal: boolean,
): void {
  if (isGlobal) {
    log.info('Append the following to ~/.claude/CLAUDE.md:');
    log.info('\n' + generateClaudeGlobal());
    copyVendoredRuntime(path.join(process.env.HOME ?? '~', '.claude'), pluginRoot);
    deployClaudePlugin(
      path.join(process.env.HOME ?? '~', '.claude'),
      pluginRoot,
      projectRoot,
      true,
    );
  } else {
    copyVendoredRuntime(projectRoot, pluginRoot);
    fs.writeFileSync(
      path.join(projectRoot, 'CLAUDE.md'),
      generateClaudeMd(indexContent, projectName),
    );
    log.success('Generated CLAUDE.md');
    deployClaudePlugin(path.join(projectRoot, '.claude'), pluginRoot, projectRoot, false);
  }
}

// Deploy the full MPGA plugin into a .claude/ directory:
//   skills/mpga-<name>/SKILL.md  (11 skills)
//   agents/<slug>.md             (10 agents)
//   commands/<cmd>.md            (21 /mpga:* commands)
//   settings.json                (hooks merged with existing)
function deployClaudePlugin(
  claudeDir: string,
  pluginRoot: string | null,
  projectRoot: string,
  isGlobal: boolean,
): void {
  fs.mkdirSync(claudeDir, { recursive: true });

  const cliPath = pluginRoot
    ? isGlobal
      ? globalVendoredCliCommand(claudeDir)
      : projectVendoredCliCommand()
    : undefined;

  // Skills
  copySkillsTo(path.join(claudeDir, 'skills'), pluginRoot, 'claude', cliPath);
  log.success(`.claude/skills/ (${SKILL_NAMES.length} skills)`);

  if (!pluginRoot) {
    log.warn(
      'Plugin root not found — skipping agents, commands, and hooks. Set MPGA_PLUGIN_ROOT to fix.',
    );
    return;
  }

  // Agents
  const agentsSrc = path.join(pluginRoot, 'agents');
  const agentsDest = path.join(claudeDir, 'agents');
  if (fs.existsSync(agentsSrc)) {
    fs.mkdirSync(agentsDest, { recursive: true });
    for (const f of fs.readdirSync(agentsSrc).filter((n) => n.endsWith('.md'))) {
      const content = rewriteCliReferences(
        fs.readFileSync(path.join(agentsSrc, f), 'utf-8'),
        cliPath,
      );
      fs.writeFileSync(path.join(agentsDest, f), content);
    }
    log.success(
      `.claude/agents/ (${fs.readdirSync(agentsSrc).filter((n) => n.endsWith('.md')).length} agents)`,
    );
  }

  // Commands (project-scoped only — global commands go in ~/.claude/commands/)
  if (!isGlobal) {
    const commandsSrc = path.join(pluginRoot, 'commands');
    const commandsDest = path.join(claudeDir, 'commands');
    if (fs.existsSync(commandsSrc)) {
      fs.mkdirSync(commandsDest, { recursive: true });
      for (const f of fs.readdirSync(commandsSrc).filter((n) => n.endsWith('.md'))) {
        // Resolve ${CLAUDE_PLUGIN_ROOT} in command files too
        let content = fs.readFileSync(path.join(commandsSrc, f), 'utf-8');
        if (cliPath) {
          content = rewriteCliReferences(content, cliPath);
        }
        fs.writeFileSync(path.join(commandsDest, f), content);
      }
      log.success(
        `.claude/commands/ (${fs.readdirSync(commandsSrc).filter((n) => n.endsWith('.md')).length} /mpga:* commands)`,
      );
    }
  }

  // Hooks → merged into settings.json
  const hooksSrc = path.join(pluginRoot, 'hooks', 'hooks.json');
  if (fs.existsSync(hooksSrc)) {
    const settingsPath = path.join(claudeDir, 'settings.json');
    const hooks = JSON.parse(fs.readFileSync(hooksSrc, 'utf-8'));

    // Rewrite local/plugin CLI references to the portable vendored command.
    const hooksStr = rewriteCliReferences(JSON.stringify(hooks), cliPath, pluginRoot);
    const resolvedHooks = JSON.parse(hooksStr);

    let settings: Record<string, unknown> = {};
    if (fs.existsSync(settingsPath)) {
      try {
        settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
      } catch {
        /* ignore */
      }
    }
    // Replace hooks entirely (not append) to avoid duplicates on re-export
    const merged = resolvedHooks.hooks ?? {};
    settings.hooks = merged;
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    log.success('.claude/settings.json (hooks configured)');
  }
}

function generateClaudeMd(indexContent: string, _projectName: string): string {
  const milestonesMatch = indexContent.match(/## Active milestone\n([\s\S]*?)(?=\n##|$)/);
  const milestone = milestonesMatch ? milestonesMatch[1].trim() : '(none)';

  return `# MPGA-Managed Project Context

This project uses MPGA for evidence-backed context engineering.
Do NOT edit this file manually — generated from MPGA/INDEX.md.
Run \`mpga sync && mpga export --claude\` to update.

## Key rules
- ALWAYS read MPGA/INDEX.md before starting any task
- ALWAYS cite evidence links [E] when making claims about code
- NEVER write implementation before tests (TDD enforced)
- Mark anything unverified as [Unknown]
- Allow parallel READS, not parallel WRITES: one writer per scope, scouts/auditors in background
- Prefer scope-local work queues so independent scopes can move in parallel

## Available MPGA commands
- /mpga:status — project health dashboard
- /mpga:board — task board
- /mpga:plan — evidence-based planning
- /mpga:execute — TDD cycle execution
- /mpga:quick "<task>" — ad-hoc task with TDD

## Scope registry
Read MPGA/INDEX.md for the full scope registry and agent trigger table.

## Active milestone
${milestone}

Generated: ${new Date().toISOString()}
`;
}

function generateClaudeGlobal(): string {
  return `## MPGA Global Rules

When you detect an MPGA/ directory in any project:
1. Read MPGA/INDEX.md first — it is the project's truth map
2. Use evidence links [E] to ground every code claim
3. Mark unknowns explicitly as [Unknown]
4. Follow the TDD cycle: red-dev → green-dev → blue-dev
5. Check MPGA/board/BOARD.md for current task state
6. Run \`mpga drift --quick\` after modifying files
7. Update scope docs when code changes affect evidence links
8. Use one writer per scope; scouts and auditors may run in parallel as read-only helpers
`;
}
